### ISSUE TITLE
Deciding the tech stack

### ISSUE THREAD

**Issue by carsonsturtevant** [thefinch/A-Productive-Distraction#1]
What technology stack would best suit this type of game? Should it be a mobile based game, web, windows, etc?
- [x] Investigate possible JS engines other than Phaser

**Comment by Evie-Skinner18** [comment]
I vote for something mobile or browser based as opposed to Unity/other heavyweight game engine 🤓

**Comment by carsonsturtevant** [comment]
> I vote for something mobile or browser based as opposed to Unity/other heavyweight game engine 🤓

thefinch suggested Phaser.IO. Do you have any experience with that framework? I think it would suit the project well.

**Comment by thefinch** [comment]
Unity would be great if we were targeting consoles/Steam or anything like that, but the intention of this project is to be relatively simple both for my own sanity (since I'm a web developer not a game developer) and so that it's easy for newbies of all types to get involved with.

As Carson mentioned, I had mentioned https://phaser.io previously since I have a little experience with it. It seemed reasonably easy to work with so I thought it might fit for this. I haven't really done any research for other browser based engines though so I'm still open to suggestions!

**Comment by Evie-Skinner18** [comment]
Brill Phaser looks great, no experience with that yet. My game development experience so far has been vanilla JS without the canvas

**Comment by thefinch** [comment]
Stumbled on this: https://github.com/collections/javascript-game-engines. Looks like there’s a few out there, but Phaser is the 2nd most popular. 1st is Pixi (https://www.pixijs.com/) and while I haven’t tried it before, it looks like it might be a solid option. I believe at one point it was used by Phaser if it’s not still the case.

**Comment by Evie-Skinner18** [comment]
Yep happy to go with Pixi no worries!

**Comment by thefinch** [comment]
Looks like we've settled on Phaser for now.
